export const COUPON_CODES = {
  BFRIDAY: "BFRIDAY",
  BFRIDAY2: "BFRIDAY2",
  BFRIDAY3: "BFRIDAY3",
  BFRIDAY4: "BFRIDAY4",
  BFRIDAY5: "BFRIDAY5",
  BFRIDAY6: "BFRIDAY6",
  BFRIDAY7: "BFRIDAY7",
  BFRIDAY8: "BFRIDAY8",
  BFRIDAY9: "BFRIDAY9",
  BFRIDAY10: "BFRIDAY10",
}

export type CouponCode = keyof typeof COUPON_CODES;
